### ISSUE TITLE
Firefoxでのコメント表示

### ISSUE THREAD

**Issue by todaif** [mohemohe/kusa5.mod.user.js#1]
Firefoxで当スクリプトを使用した場合、
下部に固定表示するタイプのコメントが
一定時間経過しても消えず表示が残り続けています。

**Comment by mohemohe** [comment]
使用しているFirefoxのバージョンとUserScript実行エンジンは何でしょうか。
Firefox 44.0 および Firefox Developer Edition 45.0a2 と Greasemonkey 3.6 で正常に動作することを確認しています。
Scriptishでの動作は保証していません。

**Comment by todaif** [comment]
返信の内容からこちらの環境に問題あるとわかり、Firefoxをリフレッシュしたところ正常に動作しました。
おそらくアドオンか何かが悪さをしていたんだと思います。
返信ありがとうございました。

**Comment by mohemohe** [comment]
動作したようでよかったです。
ページの要素を書き換え続けているので、ページの要素を監視して変更するアドオンとは相性が悪いことがあるかもしれません。
uBlockと併用しても相性問題は起こらなかったので、どのようなアドオンが該当するのかは分かりませんが…
もしまた何か問題が起きた場合はissueを立てていただけると幸いです。
