### ISSUE TITLE
「モニターサイズでフルスクリーンにする」は一般会員でも出来るのでは？

### ISSUE THREAD

**Issue by atnanasi** [mohemohe/kusa5.mod.user.js#13]
![image](https://cloud.githubusercontent.com/assets/6058487/15090061/65b3677c-1452-11e6-8a9d-1cd902e6efe8.png)
どうでしょうか？

**Comment by mohemohe** [comment]
なるほど
今はモニターサイズの拡大が一般会員でもできるようになってるんですね
次のリリースで直します
