### ISSUE TITLE
ボリュームを操作しないと音が出ない

### ISSUE THREAD

**Issue by k725** [mohemohe/kusa5.mod.user.js#2]
Chromeだと動画読み込み後ボリュームを触らないと音が出ません＞＜

// 既知のバグだったらごめんなさい

**Comment by mohemohe** [comment]
Chromeだと、というよりも動作がもたついたときに発生してる気が
（マイリス・広告のメニューとか下部再生リストの表示とかがページ読み込み後に発生してとても重い）
初期化時だけじゃなくて再生開始直前にももう1回localStorageから読み込んでみるといいかもしれない？

**Comment by k725** [comment]
今更ですが 0dc468b5161d80e333248790c45f466ac8aca6d2 にて直ってるのを確認しました。
