### ISSUE TITLE
フルスクリーン時にプレイヤー下部が隠れない

### ISSUE THREAD

**Issue by hazkyoko** [mohemohe/kusa5.mod.user.js#5]
マウスカーソルをプレイヤー外に移動させれば
下部のシークバー等の操作部が隠れるようになってますが
フルスクリーンの場合プレイヤー外にカーソルが出ることができないので
隠れず出っぱなしになってしまいます

フルスクリーンを選択したあとカーソルを動かさなければ隠れるのですが
今度はカーソルを邪魔にならない場所に退避させることができないですね…
元々半透明なのでそこまで邪魔になるものではないですし
現時点で十分ありがたいスクリプトなのでお手を煩わせるのも気がひけるのですが
気が向いた時にでも対応していただけると嬉しいです

**Comment by mohemohe** [comment]
フルスクリーンの場合はマウスが移動したときに表示させるように変更します。

**Comment by hazkyoko** [comment]
返信ありがとうございます
更新を楽しみにしています

**Comment by hazkyoko** [comment]
返信遅くなりました、対応ありがとうございます
きちんとフルスクリーンでも隠れるようになり、動作しっかり動いています
Zenzaと併用してこれからも使わせていただきます
