### ISSUE TITLE
再生ボタンと停止ボタンが逆なのでは？

### ISSUE THREAD

**Issue by taraba184** [mohemohe/kusa5.mod.user.js#8]
現在、再生中は「>」ボタン、停止中は「II」ボタンが表示されていますが、これは逆なのではないでしょうか？
どのメディアプレイヤーも再生中は停止させるためのボタンを表示し、停止中は再生するボタンを表示するようになっています。
動画の再生自体は問題なく行われています。

Ubuntu 14.04 64bit 
Firefox 45.0 + Greasemonkey 3.7
Vivaldi 1.0.429.5 + Violent monkey 2.2.6

**Comment by mohemohe** [comment]
私も以前から逆ではないか逆ではないかと思っていたのですが、やはり逆ですよね
ちょっと引っ越し後でごたごたしてるのですが、これはすぐ直せるので近日中に直します

**Comment by taraba184** [comment]
version 38 にて修正を確認しました。
ありがとうございました。
